site_name: SIMPLEX JAVA
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate

    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo

plugins:
  - tags
  - search


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aleksandre-zaccone
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aablotia/
  generator: false

markdown_extensions:
 # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: |
  &copy; 2023 <a href="https://github.com/aleksandre-zaccone"> Aleksandre Zaccone</a>
